// Code generated by protoc-gen-go.
// source: main.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	main.proto

It has these top-level messages:
	PlayerStatus
	SquareValue
	BoardUpdate
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_READY      Status = 0
	Status_UNREADY    Status = 1
	Status_DISCONNECT Status = 2
)

var Status_name = map[int32]string{
	0: "READY",
	1: "UNREADY",
	2: "DISCONNECT",
}
var Status_value = map[string]int32{
	"READY":      0,
	"UNREADY":    1,
	"DISCONNECT": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SquareType int32

const (
	SquareType_Empty    SquareType = 0
	SquareType_Mountain SquareType = 1
	SquareType_Town     SquareType = 2
	SquareType_Capital  SquareType = 3
)

var SquareType_name = map[int32]string{
	0: "Empty",
	1: "Mountain",
	2: "Town",
	3: "Capital",
}
var SquareType_value = map[string]int32{
	"Empty":    0,
	"Mountain": 1,
	"Town":     2,
	"Capital":  3,
}

func (x SquareType) String() string {
	return proto.EnumName(SquareType_name, int32(x))
}
func (SquareType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PlayerStatus struct {
	Status Status `protobuf:"varint,1,opt,name=status,enum=main.Status" json:"status,omitempty"`
}

func (m *PlayerStatus) Reset()                    { *m = PlayerStatus{} }
func (m *PlayerStatus) String() string            { return proto.CompactTextString(m) }
func (*PlayerStatus) ProtoMessage()               {}
func (*PlayerStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PlayerStatus) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_READY
}

type SquareValue struct {
	Owner  int32      `protobuf:"varint,1,opt,name=owner" json:"owner,omitempty"`
	Troops int32      `protobuf:"varint,2,opt,name=troops" json:"troops,omitempty"`
	Type   SquareType `protobuf:"varint,3,opt,name=type,enum=main.SquareType" json:"type,omitempty"`
}

func (m *SquareValue) Reset()                    { *m = SquareValue{} }
func (m *SquareValue) String() string            { return proto.CompactTextString(m) }
func (*SquareValue) ProtoMessage()               {}
func (*SquareValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SquareValue) GetOwner() int32 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *SquareValue) GetTroops() int32 {
	if m != nil {
		return m.Troops
	}
	return 0
}

func (m *SquareValue) GetType() SquareType {
	if m != nil {
		return m.Type
	}
	return SquareType_Empty
}

type BoardUpdate struct {
	Row     []*BoardUpdateInnerRow `protobuf:"bytes,1,rep,name=row" json:"row,omitempty"`
	Players []string               `protobuf:"bytes,2,rep,name=players" json:"players,omitempty"`
}

func (m *BoardUpdate) Reset()                    { *m = BoardUpdate{} }
func (m *BoardUpdate) String() string            { return proto.CompactTextString(m) }
func (*BoardUpdate) ProtoMessage()               {}
func (*BoardUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BoardUpdate) GetRow() []*BoardUpdateInnerRow {
	if m != nil {
		return m.Row
	}
	return nil
}

func (m *BoardUpdate) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

type BoardUpdateInnerRow struct {
	Value []*SquareValue `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *BoardUpdateInnerRow) Reset()                    { *m = BoardUpdateInnerRow{} }
func (m *BoardUpdateInnerRow) String() string            { return proto.CompactTextString(m) }
func (*BoardUpdateInnerRow) ProtoMessage()               {}
func (*BoardUpdateInnerRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *BoardUpdateInnerRow) GetValue() []*SquareValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*PlayerStatus)(nil), "main.playerStatus")
	proto.RegisterType((*SquareValue)(nil), "main.squareValue")
	proto.RegisterType((*BoardUpdate)(nil), "main.boardUpdate")
	proto.RegisterType((*BoardUpdateInnerRow)(nil), "main.boardUpdate.innerRow")
	proto.RegisterEnum("main.Status", Status_name, Status_value)
	proto.RegisterEnum("main.SquareType", SquareType_name, SquareType_value)
}

func init() { proto.RegisterFile("main.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x51, 0x41, 0x6b, 0x32, 0x31,
	0x14, 0x74, 0x5d, 0x77, 0xd5, 0xb7, 0x22, 0xf9, 0x1e, 0x1f, 0x65, 0xf1, 0x24, 0x22, 0x54, 0xa4,
	0x48, 0xd1, 0x1e, 0x7b, 0x29, 0xea, 0xa1, 0x87, 0x5a, 0x88, 0x5a, 0xe8, 0x31, 0x62, 0x0e, 0x0b,
	0x6b, 0x92, 0x66, 0xb3, 0x5d, 0xf6, 0x2f, 0xf4, 0x57, 0x97, 0x24, 0x2b, 0xf5, 0xf6, 0x26, 0xf3,
	0x66, 0x26, 0x93, 0x00, 0x5c, 0x58, 0x26, 0x16, 0x4a, 0x4b, 0x23, 0xb1, 0x63, 0xe7, 0xc9, 0x13,
	0x0c, 0x54, 0xce, 0x6a, 0xae, 0xf7, 0x86, 0x99, 0xb2, 0xc0, 0x29, 0xc4, 0x85, 0x9b, 0xd2, 0x60,
	0x1c, 0xcc, 0x86, 0xcb, 0xc1, 0xc2, 0x49, 0x3c, 0x4b, 0x1b, 0x6e, 0xc2, 0x20, 0x29, 0xbe, 0x4a,
	0xa6, 0xf9, 0x07, 0xcb, 0x4b, 0x8e, 0xff, 0x21, 0x92, 0x95, 0xe0, 0xda, 0x69, 0x22, 0xea, 0x01,
	0xde, 0x41, 0x6c, 0xb4, 0x94, 0xaa, 0x48, 0xdb, 0xee, 0xb8, 0x41, 0x38, 0x85, 0x8e, 0xa9, 0x15,
	0x4f, 0x43, 0x17, 0x40, 0x7c, 0x80, 0xb7, 0x3b, 0xd4, 0x8a, 0x53, 0xc7, 0x4e, 0x7e, 0x02, 0x48,
	0x4e, 0x92, 0xe9, 0xf3, 0x51, 0x9d, 0x99, 0xe1, 0xf8, 0x00, 0xa1, 0x96, 0x55, 0x1a, 0x8c, 0xc3,
	0x59, 0xb2, 0x1c, 0x79, 0xd1, 0x0d, 0xbf, 0xc8, 0x84, 0xe0, 0x9a, 0xca, 0x8a, 0xda, 0x35, 0x4c,
	0xa1, 0xeb, 0x6b, 0xd9, 0xf0, 0x70, 0xd6, 0xa7, 0x57, 0x38, 0x5a, 0x41, 0xef, 0xba, 0x8a, 0xf7,
	0x10, 0x7d, 0xdb, 0x02, 0x8d, 0xeb, 0xbf, 0xdb, 0xab, 0xb8, 0x66, 0xd4, 0xf3, 0xf3, 0x47, 0x88,
	0x9b, 0xf7, 0xe9, 0x43, 0x44, 0xb7, 0x2f, 0x9b, 0x4f, 0xd2, 0xc2, 0x04, 0xba, 0xc7, 0x9d, 0x07,
	0x01, 0x0e, 0x01, 0x36, 0xaf, 0xfb, 0xf5, 0xfb, 0x6e, 0xb7, 0x5d, 0x1f, 0x48, 0x7b, 0xfe, 0x0c,
	0xf0, 0x57, 0xc9, 0xaa, 0xb6, 0x17, 0x65, 0x6a, 0xd2, 0xc2, 0x01, 0xf4, 0xde, 0x64, 0x29, 0x0c,
	0xcb, 0x04, 0x09, 0xb0, 0x07, 0x9d, 0x83, 0xac, 0x04, 0x69, 0x5b, 0xb7, 0x35, 0x53, 0x99, 0x61,
	0x39, 0x09, 0x4f, 0xb1, 0xfb, 0xa2, 0xd5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x81, 0xa0,
	0xb5, 0xb0, 0x01, 0x00, 0x00,
}
